# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NexusV < Formula
  desc "A modern VS Code extension scaffolder with zero runtime dependencies."
  homepage "https://github.com/stillsystems/nexus-v"
  version "0.2.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stillsystems/nexus-v/releases/download/v0.2.9/nexus-v_darwin_amd64.tar.gz"
      sha256 "f92dbdc4c4b7d5cafc893cff14c0ffafcadb4ee869a4ca037a5c35b8c2858584"

      define_method(:install) do
        bin.install "nexus-v"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stillsystems/nexus-v/releases/download/v0.2.9/nexus-v_darwin_arm64.tar.gz"
      sha256 "6466306f6c8166fe87527c59596c68ff33cd9808d7a10ee306747bab19530122"

      define_method(:install) do
        bin.install "nexus-v"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stillsystems/nexus-v/releases/download/v0.2.9/nexus-v_linux_amd64.tar.gz"
      sha256 "4e28ce6db71668611ab83cb53a073d02e0dd6abbe926558a336bc93db0ef3312"
      define_method(:install) do
        bin.install "nexus-v"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stillsystems/nexus-v/releases/download/v0.2.9/nexus-v_linux_arm64.tar.gz"
      sha256 "f3d3842a06afdb43089a036cccde1bf95584f1573a545fcde9bf928564d75b6b"
      define_method(:install) do
        bin.install "nexus-v"
      end
    end
  end
end
