# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NexusV < Formula
  desc "A modern VS Code extension scaffolder with zero runtime dependencies."
  homepage "https://github.com/stillsystems/nexus-v"
  version "0.2.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stillsystems/nexus-v/releases/download/v0.2.10/nexus-v_darwin_amd64.tar.gz"
      sha256 "23301292f25480bd8603ef76dce07e2227184a9958bae16b48330a140197dabc"

      define_method(:install) do
        bin.install "nexus-v"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stillsystems/nexus-v/releases/download/v0.2.10/nexus-v_darwin_arm64.tar.gz"
      sha256 "f39923411bdfb0e50970078b4ad1b4b2ccb0b43ee9d30cc53924332ecdcc87b2"

      define_method(:install) do
        bin.install "nexus-v"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stillsystems/nexus-v/releases/download/v0.2.10/nexus-v_linux_amd64.tar.gz"
      sha256 "97bdf8b1ed5988b5d0d323e89f86a01d9ee79b9013c2955c9406075fd38bb801"
      define_method(:install) do
        bin.install "nexus-v"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stillsystems/nexus-v/releases/download/v0.2.10/nexus-v_linux_arm64.tar.gz"
      sha256 "656a2c896ba9aae7568e2ec15f30ad3ae30ac6bb887940dbd9aef9e41baae4e5"
      define_method(:install) do
        bin.install "nexus-v"
      end
    end
  end
end
